name: Pulumi outputs
description: Get resource output from Pulumi application for defined inputs
inputs:
  organization:
    description: Organization name
    required: true
  project:
    description: Project name
  stack:
    description: Stack name
    required: true
  resource:
    description: Resource name
    required: false
  resources:
    description: Resource names
    required: false
  access-token:
    description: Pulumi access token
    required: true
outputs:
  resource-output:
    description: The requested resource output from Pulumi
runs:
  using: node16
  main: index.js
