name: 'Pulumi outputs'
description: 'Get outputs from pulumi applications for defined inputs'
inputs:
  pulumi-organization:
    description: 'Pulumi organization name (lowercase)'
    required: true
  pulumi-project:
    description: 'Pulumi project (lowercase)'
  pulumi-stack:
    description: 'Pulumi stack'
    required: true
  pulumi-resource:
    description: 'The output variable'
    required: true
  pulumi-access-token:
    description: 'Your access token for accesssing Pulumi'
    required: true
outputs:
  resource-output:
    description: 'The requested resource output from Pulumi'
runs:
  using: 'node16'
  main: 'index.js'
