on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing testing
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Testing pulumi outputs
        id: test
        uses: ./
        with:
          organization: virtualfinland
          project: authentication-gw
          stack: dev
          resources: |
            endpoint
            dynamoDBCacheTableName
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Get the output
        run: echo 'The 1nd output was ${{ steps.test.outputs.resource-outputs.endpoint }} and the 2nd output was ${{ steps.test.outputs.resource-outputs.dynamoDBCacheTableName }}'
      - name: Testing old pulumi outputs
        id: old-test
        uses: ./
        with:
          organization: virtualfinland
          project: authentication-gw
          stack: dev
          resource: endpoint
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Get the output
        run: echo 'The output was ${{ steps.old-test.outputs.resource-output }}'
